version: "3.8"
networks:
  default:
    external:
      name: micronet
services:
  # # # Sicpa Sericer Api
  sicpaservicesapi:
    container_name: sicpaservicesapi
    image: devlamo/sicpaservicesapi:v0.2.3
    restart: unless-stopped
    ports:
      - "40100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ConnectionDb=Server=vm-postgres;Database=sicpadb;Port=5432;User Id=postgres;Password=sicpa1234;
  # # # Postgress Database
  db:
    container_name: vm-postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: sicpa1234
  # # # Database Adminer
  adminer:
    container_name: db-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
